# Introduction

In this notebook, we will do a comprehensive analysis of the Android app market by comparing thousands of apps in the Google Play store.

# About the Dataset of Google Play Store Apps & Reviews

**Data Source:** <br>
App and review data was scraped from the Google Play Store by Lavanya Gupta in 2018. Original files listed [here](
https://www.kaggle.com/lava18/google-play-store-apps).

# Import Statements

In [1]:
import pandas as pd
import plotly.express as px

# Notebook Presentation

In [2]:
# Show numeric output in decimal format e.g., 2.15
pd.options.display.float_format = '{:,.2f}'.format

# Read the Dataset

In [3]:
df_apps = pd.read_csv('apps.csv')

# Data Cleaning

**Challenge**: How many rows and columns does `df_apps` have? What are the column names? Look at a random sample of 5 different rows with [.sample()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html).

In [4]:
df_apps.shape

(10841, 12)

In [5]:
df_apps.sample()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
7637,Pic Stitch - #1 Collage Maker,PHOTOGRAPHY,4.20,15426,50.00,"1,000,000",Free,0,Everyone,Photography,"July 24, 2018",5.1 and up

### Drop Unused Columns

**Challenge**: Remove the columns called `Last_Updated` and `Android_Version` from the DataFrame. We will not use these columns.

In [6]:
df_apps.drop(columns=['Last_Updated','Android_Ver'], inplace=True, axis=1)

In [7]:
df_apps.sample()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
7745,Hypocam,PHOTOGRAPHY,4.50,12572,8.50,"1,000,000",Free,0,Everyone,Photography

### Find and Remove NaN values in Ratings

**Challenge**: How may rows have a NaN value (not-a-number) in the Ratings column? Create DataFrame called `df_apps_clean` that does not include these rows.

In [8]:
df_apps['Rating'].isnull().sum()

np.int64(1474)

In [9]:
df_apps_clean = df_apps.dropna(subset=['Rating'])
df_apps_clean.isnull().values.any()

np.False_

### Find and Remove Duplicates

**Challenge**: Are there any duplicates in data? Check for duplicates using the [.duplicated()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html) function. How many entries can you find for the "Instagram" app? Use [.drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) to remove any duplicates from `df_apps_clean`.

In [10]:
df_apps_clean.duplicated().any()
duplicated_rows = df_apps_clean[df_apps_clean.duplicated()]
print(duplicated_rows.shape)
duplicated_rows.head()

(476, 10)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
946,420 BZ Budeze Delivery,MEDICAL,5.00,2,11.00,100,Free,0,Mature 17+,Medical
1133,MouseMingle,DATING,2.70,3,3.90,100,Free,0,Mature 17+,Dating
1196,"Cardiac diagnosis (heart rate, arrhythmia)",MEDICAL,4.40,8,6.50,100,Paid,$12.99,Everyone,Medical
1231,Sway Medical,MEDICAL,5.00,3,22.00,100,Free,0,Everyone,Medical
1247,Chat Kids - Chat Room For Kids,DATING,4.70,6,4.90,100,Free,0,Mature 17+,Dating

In [11]:
df_apps_clean.drop_duplicates()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,$1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,$0.99,Everyone,Arcade
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0,Everyone,Arcade
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0,Everyone,Medical
...,...,...,...,...,...,...,...,...,...,...
10835,Subway Surfers,GAME,4.50,27722264,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10836,Subway Surfers,GAME,4.50,27723193,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10837,Subway Surfers,GAME,4.50,27724094,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10838,Subway Surfers,GAME,4.50,27725352,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10840,Subway Surfers,GAME,4.50,27711703,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade

In [12]:
df_apps_clean.duplicated().any()
df_apps_clean[df_apps_clean.App == 'Instagram']

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10808,Instagram,SOCIAL,4.50,66577446,5.30,"1,000,000,000",Free,0,Teen,Social
10809,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10810,Instagram,SOCIAL,4.50,66509917,5.30,"1,000,000,000",Free,0,Teen,Social

In [13]:
df_apps_clean = df_apps_clean.drop_duplicates(subset=['App', 'Type', 'Price'])

In [14]:
df_apps_clean.shape

(8199, 10)

In [15]:
df_apps_clean[df_apps_clean.App == 'Instagram']

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social

# Find Highest Rated Apps

**Challenge**: Identify which apps are the highest rated. What problem might you encounter if you rely exclusively on ratings alone to determine the quality of an app?

In [16]:
df_apps_clean['Rating'].max()
df_highest = df_apps_clean[df_apps_clean['Rating'] == 5]
df_highest

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,$1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,$0.99,Everyone,Arcade
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0,Everyone,Arcade
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0,Everyone,Medical
...,...,...,...,...,...,...,...,...,...,...
2680,Florida Wildflowers,FAMILY,5.00,5,69.00,"1,000",Free,0,Everyone,Education
2750,"Superheroes, Marvel, DC, Comics, TV, Movies News",COMICS,5.00,34,12.00,"5,000",Free,0,Everyone,Comics
3030,CL Keyboard - Myanmar Keyboard (No Ads),TOOLS,5.00,24,3.20,"5,000",Free,0,Everyone,Tools
3115,Oración CX,LIFESTYLE,5.00,103,3.80,"5,000",Free,0,Everyone,Lifestyle
4058,Ek Bander Ne Kholi Dukan,FAMILY,5.00,10,3.00,"10,000",Free,0,Everyone,Entertainment

# Find 5 Largest Apps in terms of Size (MBs)

**Challenge**: What's the size in megabytes (MB) of the largest Android apps in the Google Play Store. Based on the data, do you think there could be limit in place or can developers make apps as large as they please?

In [17]:
df_sorted = df_apps_clean.sort_values(ascending=False, by=['Size_MBs'])
df_sorted.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
8719,Draft Simulator for FUT 18,SPORTS,4.60,162933,100.00,"5,000,000",Free,0,Everyone,Sports
8718,Mini Golf King - Multiplayer Game,GAME,4.50,531458,100.00,"5,000,000",Free,0,Everyone,Sports
10295,SimCity BuildIt,FAMILY,4.50,4218587,100.00,"50,000,000",Free,0,Everyone 10+,Simulation
9945,Ultimate Tennis,SPORTS,4.30,183004,100.00,"10,000,000",Free,0,Everyone,Sports
9944,Gangster Town: Vice District,FAMILY,4.30,65146,100.00,"10,000,000",Free,0,Mature 17+,Simulation

# Find the 5 App with Most Reviews

**Challenge**: Which apps have the highest number of reviews? Are there any paid apps among the top 50?

In [18]:
df_sorted = df_apps_clean.sort_values(ascending=False, by=['Reviews'])
df_sorted.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10805,Facebook,SOCIAL,4.10,78158306,5.30,"1,000,000,000",Free,0,Teen,Social
10785,WhatsApp Messenger,COMMUNICATION,4.40,69119316,3.50,"1,000,000,000",Free,0,Everyone,Communication
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10784,Messenger – Text and Video Chat for Free,COMMUNICATION,4.00,56642847,3.50,"1,000,000,000",Free,0,Everyone,Communication
10650,Clash of Clans,GAME,4.60,44891723,98.00,"100,000,000",Free,0,Everyone 10+,Strategy

# Plotly Pie and Donut Charts - Visualise Categorical Data: Content Ratings

In [19]:
ratings = df_apps_clean.Content_Rating.value_counts()
ratings

Content_Rating
Everyone           6621
Teen                912
Mature 17+          357
Everyone 10+        305
Adults only 18+       3
Unrated               1
Name: count, dtype: int64

In [20]:
fig = px.pie(labels=ratings.index, values=ratings.values, title='Content Rating', names=ratings.index)
fig.update_traces(textposition='outside', textinfo='percent+label')
fig.show()

In [21]:
# Dount shape
fig = px.pie(labels=ratings.index, values=ratings.values, title='Content Rating', names=ratings.index, hole=0.6)
fig.update_traces(textposition='outside', textinfo='percent+label')
fig.show()

# Numeric Type Conversion: Examine the Number of Installs

**Challenge**: How many apps had over 1 billion (that's right - BILLION) installations? How many apps just had a single install?

Check the datatype of the Installs column.

Count the number of apps at each level of installations.

Convert the number of installations (the Installs column) to a numeric data type. Hint: this is a 2-step process. You'll have make sure you remove non-numeric characters first.

In [22]:
df_apps_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8199 entries, 21 to 10835
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8199 non-null   object
 1   Category        8199 non-null   object
 2   Rating          8199 non-null   float64
 3   Reviews         8199 non-null   int64
 4   Size_MBs        8199 non-null   float64
 5   Installs        8199 non-null   object
 6   Type            8199 non-null   object
 7   Price           8199 non-null   object
 8   Content_Rating  8199 non-null   object
 9   Genres          8199 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 704.6+ KB

In [23]:
type(df_apps_clean['Installs'].iloc[1])

str

In [24]:
df_apps_clean['Installs'] = df_apps_clean['Installs'].str.replace(r'\D+', '', regex=True)

df_sorted = df_apps_clean.sort_values(ascending=False, by=['Price'])
df_sorted.head(150)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
7182,Pushbullet - SMS on PC,PRODUCTIVITY,4.50,176873,4.50,1000000,Free,0,Everyone,Productivity
7196,Al Quran Audio (Full 30 Juz),FAMILY,4.70,7878,3.60,1000000,Free,0,Everyone,Education
7195,Funny Quotes Free,ENTERTAINMENT,4.20,23666,3.60,1000000,Free,0,Teen,Entertainment
7194,EX File Explorer File Manager,PRODUCTIVITY,4.00,4660,5.90,1000000,Free,0,Everyone,Productivity
...,...,...,...,...,...,...,...,...,...,...
7314,Financial Calculator India,FINANCE,4.60,13819,3.90,1000000,Free,0,Everyone,Finance
7313,Police Detector (Speed Camera Radar),AUTO_AND_VEHICLES,4.30,3574,3.90,1000000,Free,0,Everyone 10+,Auto & Vehicles
7312,Baby Sleep: White noise lullabies for newborns,PARENTING,4.60,62386,3.40,1000000,Free,0,Everyone,Parenting
7311,Lyra Virtual Assistant,PRODUCTIVITY,4.50,41624,3.40,1000000,Free,0,Everyone,Productivity
7310,ES App Locker,TOOLS,4.30,32207,3.40,1000000,Free,0,Everyone,Tools

In [25]:
df_apps_clean['Installs'] = pd.to_numeric(df_apps_clean['Installs'])
type(df_apps_clean['Installs'].iloc[1])

numpy.int64

In [26]:
df_apps_clean[df_apps_clean['Installs'] >= 1000000000].count()
df_apps_clean[['App', 'Installs']].groupby('Installs').count()

             App
Installs
1              3
5              9
10            69
50            56
100          303
500          199
1000         698
5000         425
10000        988
50000        457
100000      1096
500000       504
1000000     1417
5000000      607
10000000     933
50000000     202
100000000    189
500000000     24
1000000000    20

# Find the Most Expensive Apps, Filter out the Junk, and Calculate a (ballpark) Sales Revenue Estimate

Let's examine the Price column more closely.

**Challenge**: Convert the price column to numeric data. Then investigate the top 20 most expensive apps in the dataset.

Remove all apps that cost more than $250 from the `df_apps_clean` DataFrame.

Add a column called 'Revenue_Estimate' to the DataFrame. This column should hold the price of the app times the number of installs. What are the top 10 highest grossing paid apps according to this estimate? Out of the top 10 highest grossing paid apps, how many are games?

In [27]:
df_apps_clean['Price'] = df_apps_clean['Price'].str.replace('$', '')
df_apps_clean['Price'] = pd.to_numeric(df_apps_clean['Price'])
type(df_apps_clean['Price'].iloc[1])

numpy.float64

### The most expensive apps sub $250

In [28]:
df_apps_clean[['App', 'Price']][df_apps_clean['Price'] > 250].sort_values(by='Price', ascending=False).head(20)

# df_apps_clean.sort_values(by='Price', ascending=False).head()

                                 App  Price
3946        I'm Rich - Trump Edition 400.00
1946  I am rich (Most expensive app) 399.99
1331          most expensive app (H) 399.99
2775                   I Am Rich Pro 399.99
2461              I AM RICH PRO PLUS 399.99
3114                       I am Rich 399.99
2394                      I am Rich! 399.99
5765                       I am rich 399.99
3145              I am rich(premium) 399.99
3554                      💎 I'm rich 399.99
3221                  I am Rich Plus 399.99
4606               I Am Rich Premium 399.99
3897                       I Am Rich 389.99
2193             I am extremely Rich 379.99
3856                   I am rich VIP 299.99

### Highest Grossing Paid Apps (ballpark estimate)

In [29]:
df_apps_clean.drop(df_apps_clean[df_apps_clean['Price'] > 250].index, inplace=True)
df_apps_clean.sort_values(by='Price', ascending=False).head()
df_apps_clean['Revenue_Estimate'] = df_apps_clean['Price'] * df_apps_clean['Installs']
df_apps_clean.sort_values(by='Revenue_Estimate', ascending=False).head(10)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Revenue_Estimate
9220,Minecraft,FAMILY,4.50,2376564,19.00,10000000,Paid,6.99,Everyone 10+,Arcade;Action & Adventure,"69,900,000.00"
8825,Hitman Sniper,GAME,4.60,408292,29.00,10000000,Paid,0.99,Mature 17+,Action,"9,900,000.00"
7151,Grand Theft Auto: San Andreas,GAME,4.40,348962,26.00,1000000,Paid,6.99,Mature 17+,Action,"6,990,000.00"
7477,Facetune - For Free,PHOTOGRAPHY,4.40,49553,48.00,1000000,Paid,5.99,Everyone,Photography,"5,990,000.00"
7977,Sleep as Android Unlock,LIFESTYLE,4.50,23966,0.85,1000000,Paid,5.99,Everyone,Lifestyle,"5,990,000.00"
6594,DraStic DS Emulator,GAME,4.60,87766,12.00,1000000,Paid,4.99,Everyone,Action,"4,990,000.00"
6082,Weather Live,WEATHER,4.50,76593,4.75,500000,Paid,5.99,Everyone,Weather,"2,995,000.00"
6746,Card Wars - Adventure Time,FAMILY,4.30,129603,23.00,1000000,Paid,2.99,Everyone 10+,Card;Action & Adventure,"2,990,000.00"
7633,Five Nights at Freddy's,GAME,4.60,100805,50.00,1000000,Paid,2.99,Teen,Action,"2,990,000.00"
7954,Bloons TD 5,FAMILY,4.60,190086,94.00,1000000,Paid,2.99,Everyone,Strategy,"2,990,000.00"

# Plotly Bar Charts & Scatter Plots: Analysing App Categories

In [30]:
df_apps_clean.Category.nunique()

33

In [31]:
top10_category = df_apps_clean.Category.value_counts()[:10]
top10_category

Category
FAMILY             1606
GAME                910
TOOLS               719
PRODUCTIVITY        301
PERSONALIZATION     298
LIFESTYLE           297
FINANCE             296
MEDICAL             292
PHOTOGRAPHY         263
BUSINESS            262
Name: count, dtype: int64

### Vertical Bar Chart - Highest Competition (Number of Apps)

In [32]:
bar = px.bar(x = top10_category.index, y = top10_category.values)
bar.show()

### Horizontal Bar Chart - Most Popular Categories (Highest Downloads)

In [33]:
category_installs = df_apps_clean.groupby('Category').agg({'Installs': pd.Series.sum})
category_installs.sort_values('Installs', ascending=True, inplace=True)
h_bar = px.bar(x = category_installs.Installs,
               y = category_installs.index,
               orientation='h',
               title='Category Popularity', height=1000)

h_bar.update_layout(xaxis_title='Number of Downloads', yaxis_title='Category')
h_bar.show()

### Category Concentration - Downloads vs. Competition

**Challenge**:
* First, create a DataFrame that has the number of apps in one column and the number of installs in another:

<img src=https://imgur.com/uQRSlXi.png width="350">

* Then use the [plotly express examples from the documentation](https://plotly.com/python/line-and-scatter/) alongside the [.scatter() API reference](https://plotly.com/python-api-reference/generated/plotly.express.scatter.html)to create scatter plot that looks like this.

<img src=https://imgur.com/cHsqh6a.png>

*Hint*: Use the size, hover_name and color parameters in .scatter(). To scale the yaxis, call .update_layout() and specify that the yaxis should be on a log-scale like so: yaxis=dict(type='log')

In [34]:

category_concentration = df_apps_clean.groupby('Category').agg({'Installs': pd.Series.sum, 'App': pd.Series.count})
category_concentration

                        Installs   App
Category
ART_AND_DESIGN         114233100    61
AUTO_AND_VEHICLES       53129800    73
BEAUTY                  26916200    42
BOOKS_AND_REFERENCE   1665791655   169
BUSINESS               692018120   262
COMICS                  44931100    54
COMMUNICATION        11039241530   257
DATING                 140912410   134
EDUCATION              352852000   118
ENTERTAINMENT         2113660000   102
EVENTS                  15949410    45
FAMILY                4437554490  1606
FINANCE                455249400   296
FOOD_AND_DRINK         211677750    94
GAME                 13858762717   910
HEALTH_AND_FITNESS    1134006220   243
HOUSE_AND_HOME          97082000    62
LIBRARIES_AND_DEMO      52083000    64
LIFESTYLE              503611120   297
MAPS_AND_NAVIGATION    503267560   118
MEDICAL                 39162676   292
NEWS_AND_MAGAZINES    2369110650   204
PARENTING               31116110    50
PERSONALIZATION       1532352930   298
PHOTOGRAPHY           4649143130   263
PRODUCTIVITY          5788070180   301
SHOPPING              1400331540   180
SOCIAL                5487841475   203
SPORTS                1096431465   260
TOOLS                 8099724500   719
TRAVEL_AND_LOCAL      2894859300   187
VIDEO_PLAYERS         3916897200   148
WEATHER                361096500    72

In [35]:
fig = px.scatter(category_concentration, x='App', y='Installs', color='Installs', size='App', hover_name=category_concentration.index, title="Category Concentration", width=970, labels={'App': 'Number of Apps (Lower=More Concentration)'}, log_y=True)
fig.show()

# Extracting Nested Data from a Column

**Challenge**: How many different types of genres are there? Can an app belong to more than one genre? Check what happens when you use .value_counts() on a column with nested values? See if you can work around this problem by using the .split() function and the DataFrame's [.stack() method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html).

In [50]:
genres = df_apps_clean.Genres.str.split(';', expand=True)
genres.head(50)
stacked_genres = genres.stack()
num_genres = stacked_genres.value_counts().sort_values(ascending=False)
print(f"Number of genres: {len(num_genres)}")
num_genres.head(5)

Number of genres: 53

Tools            719
Education        587
Entertainment    498
Action           304
Productivity     301
Name: count, dtype: int64

# Colour Scales in Plotly Charts - Competition in Genres

**Challenge**: Can you create this chart with the Series containing the genre data?

<img src=https://imgur.com/DbcoQli.png width=400>

Try experimenting with the built in colour scales in Plotly. You can find a full list [here](https://plotly.com/python/builtin-colorscales/).

* Find a way to set the colour scale using the color_continuous_scale parameter.
* Find a way to make the color axis disappear by using coloraxis_showscale.

In [59]:
top_genres = num_genres[:15]
fig = px.bar(top_genres, x=top_genres.index, y=top_genres.values, color='count',
             color_continuous_scale=px.colors.sequential.Agsunset, title="Top Genres",
             labels={
                 'index': 'Genre Name',
                 'count': 'App Count'
             }, height=600, width=1200)
fig.update_yaxes(title_text='Number of Apps')
fig.show()

# Grouped Bar Charts: Free vs. Paid Apps per Category

In [73]:
df_apps_clean.Type.value_counts()

df_free_vs_paid = df_apps_clean.groupby(["Category", "Type"], as_index=False).agg({'App': pd.Series.count}).sort_values(by="App", ascending=False)
df_free_vs_paid.head()

     Category  Type   App
19     FAMILY  Free  1456
25       GAME  Free   834
53      TOOLS  Free   656
21    FINANCE  Free   289
31  LIFESTYLE  Free   284

**Challenge**: Use the plotly express bar [chart examples](https://plotly.com/python/bar-charts/#bar-chart-with-sorted-or-ordered-categories) and the [.bar() API reference](https://plotly.com/python-api-reference/generated/plotly.express.bar.html#plotly.express.bar) to create this bar chart:

<img src=https://imgur.com/LE0XCxA.png>

You'll want to use the `df_free_vs_paid` DataFrame that you created above that has the total number of free and paid apps per category.

See if you can figure out how to get the look above by changing the `categoryorder` to 'total descending' as outlined in the documentation here [here](https://plotly.com/python/categorical-axes/#automatically-sorting-categories-by-name-or-total-value).

In [71]:
fig = px.histogram(df_free_vs_paid, x='Category', y='App', barmode='group', labels={'App': 'Number of Apps'}, color='Type', log_y=True, title="Free vs Paid Apps by Category")
fig.show()

# Plotly Box Plots: Lost Downloads for Paid Apps

**Challenge**: Create a box plot that shows the number of Installs for free versus paid apps. How does the median number of installations compare? Is the difference large or small?

Use the [Box Plots Guide](https://plotly.com/python/box-plots/) and the [.box API reference](https://plotly.com/python-api-reference/generated/plotly.express.box.html) to create the following chart.

<img src=https://imgur.com/uVsECT3.png>

In [89]:
df_free_vs_paid_installs = df_apps_clean.groupby(["Type"], as_index=False).agg({'Installs': pd.Series.sum, 'App': pd.Series.count})
df_free_vs_paid_installs.head()

   Type     Installs   App
0  Free  75121934856  7595
1  Paid     57132382   589

In [91]:
fig = px.box(df_apps_clean, x='Type', y="Installs", log_y=True, points="all", color="Type", notched=True, title='How Many Downloads are Paid Apps Giving Up?')
fig.show()

# Plotly Box Plots: Revenue by App Category

**Challenge**: See if you can generate the chart below:

<img src=https://imgur.com/v4CiNqX.png>

Looking at the hover text, how much does the median app earn in the Tools category? If developing an Android app costs $30,000 or thereabouts, does the average photography app recoup its development costs?

Hint: I've used 'min ascending' to sort the categories.

In [113]:
df_paid_apps = df_apps_clean[df_apps_clean['Type'] == 'Paid']

In [117]:
fig = px.box(df_paid_apps, x='Category', y="Revenue_Estimate", log_y=True, title='How Much Can Paid Apps Earn?')
fig.update_layout(yaxis_title='Paid App Ballpark Revenue',
                  xaxis={'categoryorder':'min ascending'})
fig.show()

# How Much Can You Charge? Examine Paid App Pricing Strategies by Category

**Challenge**: What is the median price price for a paid app? Then compare pricing by category by creating another box plot. But this time examine the prices (instead of the revenue estimates) of the paid apps. I recommend using `{categoryorder':'max descending'}` to sort the categories.

In [118]:
median_price = df_apps_clean[df_apps_clean['Type'] == 'Paid']['Price'].median()
median_price

2.99

In [122]:
fig = px.box(df_paid_apps, x='Category', y="Price", log_y=True, title='How Much Can Paid Apps Earn?')
fig.update_layout(yaxis_title='Price',
                  xaxis={'categoryorder':'max descending'})
fig.show()